ECHO Delete old report ...
rm -r ./coverage

ECHO Restore project ...
dotnet restore AdventOfCode.sln

ECHO Build project ...
dotnet dotnet build AdventOfCode.sln --no-restore

ECHO Running tests ...
dotnet test AdventOfCode.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

ECHO Install ReportGenerator ...
dotnet tool install --global dotnet-reportgenerator-globaltool

ECHO Generating report ...
reportgenerator "-reports:./coverage/**/coverage.cobertura.xml" "-targetdir:./coverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"

ECHO Opening report ...
open "" ./coverage/index.htm