ECHO Delete old report ... 
@RD /S /Q  "./coverage/"

ECHO Restore project ... 
dotnet restore AdventOfCode.sln

ECHO Build project ... 
dotnet dotnet build AdventOfCode.sln --no-restore

ECHO Running tests ...
dotnet test AdventOfCode.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

ECHO Generating report ...
reportgenerator "-reports:./coverage/**/coverage.cobertura.xml" "-targetdir:./coverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura" "-filefilters:-*Program.cs;-*Tests.cs;-*TestFixture.cs"

ECHO Opening report ...
start "" ./coverage/index.htm